name: Go Build and Release

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build-and-release:
    runs-on: windows-latest
    steps:
      - name: Wait for tag propagation
        run: Start-Sleep -Seconds 60

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch all tags
        run: git fetch --tags

      - name: Extract version from release tag
        id: get_version
        run: |
          $tag = "${{ github.event.release.tag_name }}"
          if (-not $tag) {
            Write-Host "No tag found in release event, falling back to latest tag from git."
            $tag = git tag --sort=-creatordate | Select-Object -First 1
            if (-not $tag) {
              Write-Error "No tags found in repository."
              exit 1
            }
          }
          $version = $tag
          echo "VERSION=$version" >> $env:GITHUB_ENV
          echo "TAG_NAME=$tag" >> $env:GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24.4"

      - name: Build Project
        run: go build -ldflags "-H=windowsgui -s -w" -v -o EDxDC.exe

      - name: Prepare Release Directory
        run: |
          mkdir EDxDC
          Copy-Item -Path EDxDC.exe,LICENSE,README.md,names,bin -Destination .\EDxDC -Recurse

      - name: Create .portable file
        run: New-Item -Path .\EDxDC\.portable -ItemType File

      - name: Create Release Zip
        run: powershell Compress-Archive -Path .\EDxDC -DestinationPath .\EDxDC-${{ env.VERSION }}-portable-amd64.zip

      - name: Copy Files to Installer Directory
        run: |
          Copy-Item -Path .\EDxDC.exe,LICENSE,README.md -Destination .\installer\ -Force
          New-Item -Path .\installer\names -ItemType Directory -Force
          New-Item -Path .\installer\bin -ItemType Directory -Force
          Copy-Item -Path .\names\* -Destination .\installer\names\ -Recurse -Force
          Copy-Item -Path .\bin\* -Destination .\installer\bin\ -Recurse -Force

      - name: Install Inno Setup
        run: |
          choco install innosetup --no-progress --yes

      - name: Build Installer
        run: |
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" installer\installer.iss

      - name: Upload Release Artifact (portable)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ env.TAG_NAME }} ./EDxDC-${{ env.VERSION }}-portable-amd64.zip --clobber

      - name: Upload Release Artifact (installer)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ env.TAG_NAME }} ./installer/EDxDC-${{ env.VERSION }}-Setup.exe --clobber
