name: Go Build and Release

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build-and-release:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch all tags
        run: git fetch --tags

      - name: Extract version from latest tag
        id: get_version
        run: |
          $tags = git tag --sort=-creatordate
          if (-not $tags) {
            Write-Error "No git tags found. Please create a tag before running this workflow."
            exit 1
          }
          $latestTag = ($tags -split "`n")[0]
          $version = $latestTag -replace '^v', ''
          echo "VERSION=$version" >> $env:GITHUB_ENV
          echo "TAG_NAME=$latestTag" >> $env:GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24.4"

      - name: Build Project
        run: go build -ldflags "-H=windowsgui -s -w" -v -o EDxDC.exe

      - name: Prepare Release Directory
        run: |
          mkdir EDxDC
          Copy-Item -Path EDxDC.exe,LICENSE,README.md,names,bin -Destination .\EDxDC -Recurse

      - name: Create .portable file
        run: New-Item -Path .\EDxDC\.portable -ItemType File

      - name: Create Release Zip
        run: powershell Compress-Archive -Path .\EDxDC -DestinationPath .\EDxDC-v${{ env.VERSION }}-portable-amd64.zip

      - name: Copy Files to Installer Directory
        run: |
          Copy-Item -Path .\EDxDC.exe,LICENSE,README.md -Destination .\installer\ -Force
          New-Item -Path .\installer\names -ItemType Directory -Force
          New-Item -Path .\installer\bin -ItemType Directory -Force
          Copy-Item -Path .\names\* -Destination .\installer\names\ -Recurse -Force
          Copy-Item -Path .\bin\* -Destination .\installer\bin\ -Recurse -Force

      - name: Install Inno Setup
        run: |
          choco install innosetup --no-progress --yes

      - name: Build Installer
        run: |
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" installer\installer.iss

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./installer/EDxDC-v${{ env.VERSION }}-Setup.exe
            ./EDxDC-v${{ env.VERSION }}-portable-amd64.zip
          tag_name: ${{ env.TAG_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
